logging:
  level:
    org.springframework: INFO
    ma.emsi.zougagh: DEBUG
    com.netflix.discovery: DEBUG
    com.netflix.eureka: DEBUG
spring:
  kafka:
    bootstrap-servers: localhost:9092

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/product-db-${spring.profiles.active}-${server.port}
    serverName : localhost
    username: sa
    password : password

  jpa:
    generate-ddl: true
    show_sql: true
    hibernate:
      ddl_auto : create
  h2:
    console:
      enabled: true
      path: /h2-console


eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true           
    instance-id: ${spring.application.name}:${spring.profiles.active}:${server.port} 

  client:
    service-url:
      default-zone: http://localhost:8761
    register-with-eureka : true
    fetch-registry: true


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
